name: IFWand
version: '1.1'
main: io.github.aspwil.ifwand.IFWand
api-version: 1.19
authors: [ aspwil ]
description: Uses a wand to lock Item Frames
website: aspwil.github.io
commands:
  ifwand:
    description: Summon Item Frame Wand
    usage: /<command>
    permission: IFWand.wand
